//! ABOUT screen - product identity, scope and disclaimers.

use eframe::egui;

use super::{card, section_heading, theme};

pub fn show(ui: &mut egui::Ui) {
    egui::ScrollArea::vertical().show(ui, |ui| {
        ui.vertical_centered(|ui| {
            ui.add_space(24.0);
            ui.label(
                egui::RichText::new(crate::APP_PLATFORM)
                    .color(theme::PURPLE)
                    .strong()
                    .size(14.0),
            );
            ui.add_space(4.0);
            ui.label(
                egui::RichText::new(crate::APP_NAME)
                    .color(theme::ACCENT)
                    .strong()
                    .size(32.0),
            );
            ui.add_space(4.0);
            ui.label(
                egui::RichText::new(crate::APP_TAGLINE)
                    .color(theme::TEXT_DIM)
                    .size(14.0),
            );
            ui.add_space(6.0);
            ui.label(
                egui::RichText::new(format!(
                    "version {} · build {}",
                    crate::APP_VERSION,
                    crate::APP_BUILD
                ))
                .color(theme::TEXT_DIM)
                .size(12.0),
            );
            ui.add_space(20.0);
        });

        let width = ui.available_width().min(760.0);
        ui.vertical_centered(|ui| {
            ui.set_max_width(width);

            section_heading(ui, "Purpose");
            card().show(ui, |ui| {
                for line in [
                    "MEMO Collector is a portable forensic evidence acquisition tool for",
                    "Windows 10/11. It collects volatile and system-state evidence into a",
                    "single hashed AIF evidence container, with a full chain-of-custody",
                    "record, for later review by qualified forensic examiners.",
                ] {
                    ui.label(egui::RichText::new(line).color(theme::TEXT).size(13.0));
                }
            });

            ui.add_space(12.0);
            section_heading(ui, "Evidence Container");
            card().show(ui, |ui| {
                ui.label(
                    egui::RichText::new(crate::AIF_FORMAT_NAME)
                        .color(theme::ACCENT)
                        .size(13.0),
                );
                ui.add_space(4.0);
                for line in [
                    "Every artifact is hashed with SHA-256 during acquisition. The finished",
                    "container hash is recorded in the sidecar .sha256 file and the custody",
                    "record, and can be re-verified at any time from the INTEGRITY screen.",
                ] {
                    ui.label(egui::RichText::new(line).color(theme::TEXT).size(13.0));
                }
            });

            ui.add_space(12.0);
            section_heading(ui, "Scope & Integrity Guarantees");
            card().show(ui, |ui| {
                for line in [
                    "• Read-only acquisition - the tool never modifies host data.",
                    "• One module failing never aborts the acquisition.",
                    "• No fabrication: unavailable sources (physical RAM image, VRAM,",
                    "  CPU register state, SAM) are recorded as NOT AVAILABLE.",
                    "• No forensic conclusions - the report describes what was collected,",
                    "  never what it means.",
                    "• Demo mode produces clearly labelled synthetic data only.",
                    "• Chain-of-custody notice: integrity metadata generated by MEMO",
                    "  Collector.",
                ] {
                    ui.label(egui::RichText::new(line).color(theme::TEXT).size(13.0));
                }
            });

            ui.add_space(12.0);
            ui.label(
                egui::RichText::new(
                    "Intended for authorized use on systems you own or are permitted to examine.",
                )
                .color(theme::TEXT_DIM)
                .size(11.5),
            );
            ui.add_space(16.0);
        });
    });
}
