//! Chain-of-custody metadata and the acquisition log.
//!
//! The acquisition log records every significant acquisition event. It is
//! integrity metadata generated by MEMO Collector; it is NOT a legal
//! certification.

use serde::{Deserialize, Serialize};
use std::fs::OpenOptions;
use std::io::Write;
use std::path::Path;

fn now_rfc3339() -> String {
    chrono::Local::now().to_rfc3339_opts(chrono::SecondsFormat::Secs, true)
}

/// A single line of the acquisition log.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct LogEntry {
    pub timestamp: String,
    pub level: String,
    pub module: String,
    pub message: String,
}

/// Acquisition log writer. Appends to `logs/acquisition.log` inside the
/// staging directory while also keeping an in-memory copy for the report.
pub struct CustodyLog {
    pub entries: Vec<LogEntry>,
    path: Option<std::path::PathBuf>,
}

impl CustodyLog {
    pub fn new() -> Self {
        Self {
            entries: Vec::new(),
            path: None,
        }
    }

    /// Bind the log to a file (created inside the staging directory).
    pub fn bind(&mut self, path: &Path) {
        if let Some(parent) = path.parent() {
            let _ = std::fs::create_dir_all(parent);
        }
        self.path = Some(path.to_path_buf());
    }

    pub fn log(&mut self, level: &str, module: &str, message: &str) {
        let entry = LogEntry {
            timestamp: now_rfc3339(),
            level: level.to_string(),
            module: module.to_string(),
            message: message.to_string(),
        };
        if let Some(path) = &self.path {
            if let Ok(mut f) = OpenOptions::new().create(true).append(true).open(path) {
                let _ = writeln!(
                    f,
                    "[{}] [{}] [{}] {}",
                    entry.timestamp, entry.level, entry.module, entry.message
                );
            }
        }
        self.entries.push(entry);
    }

    pub fn info(&mut self, module: &str, message: &str) {
        self.log("INFO", module, message);
    }

    pub fn warn(&mut self, module: &str, message: &str) {
        self.log("WARN", module, message);
    }

    pub fn error(&mut self, module: &str, message: &str) {
        self.log("ERROR", module, message);
    }
}

impl Default for CustodyLog {
    fn default() -> Self {
        Self::new()
    }
}

/// Final chain-of-custody summary stored in the AIF container.
#[derive(Serialize, Deserialize, Clone, Debug, Default)]
pub struct ChainOfCustody {
    pub case_id: String,
    pub collector_version: String,
    pub hostname: String,
    pub operator: String,
    pub start_time: String,
    pub end_time: String,
    pub modules_requested: Vec<String>,
    pub modules_successful: Vec<String>,
    pub modules_failed: Vec<String>,
    pub modules_skipped: Vec<String>,
    pub warning_count: usize,
    pub artifact_count: usize,
    /// SHA-256 of the final AIF container.
    pub aif_sha256: String,
    /// Acquisition status: COMPLETED / PARTIAL / CANCELLED.
    pub status: String,
    pub notice: String,
}

impl ChainOfCustody {
    pub fn new(case_id: &str, hostname: &str, operator: &str) -> Self {
        Self {
            case_id: case_id.to_string(),
            collector_version: crate::APP_VERSION.to_string(),
            hostname: hostname.to_string(),
            operator: operator.to_string(),
            notice:
                "Integrity metadata generated by MEMO Collector. Not a legal certification."
                    .to_string(),
            ..Default::default()
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn log_records_entries() {
        let mut log = CustodyLog::new();
        log.info("engine", "acquisition started");
        log.warn("gpu", "VRAM raw acquisition unavailable");
        assert_eq!(log.entries.len(), 2);
        assert_eq!(log.entries[0].level, "INFO");
        assert_eq!(log.entries[1].module, "gpu");
    }
}
